# Generated by Django 5.2.5 on 2025-08-13 18:09

from django.conf import settings
from django.db import migrations


def set_owner(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    Mailing = apps.get_model('mailings', 'Mailing')
    Client = apps.get_model('mailings', 'Client')

    owner = User.objects.filter(is_superuser=True).first() or User.objects.first()
    if owner is None:
        # чтобы миграция не молча прошла, если нет ни одного юзера
        raise RuntimeError(
            "В базе нет пользователей. Создай хотя бы одного (createsuperuser) и повтори migrate."
        )

    Mailing.objects.filter(owner__isnull=True).update(owner=owner)
    Client.objects.filter(owner__isnull=True).update(owner=owner)


class Migration(migrations.Migration):
    dependencies = [
        ('mailings', '0002_client_owner_mailing_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(set_owner, migrations.RunPython.noop),
    ]
