# Generated by Django 5.2.5 on 2025-08-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_alter_client_owner_alter_mailing_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Почта"),
        ),
    ]
