# Generated by Django 5.2.5 on 2025-08-13 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_alter_client_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("owner", "email"), name="uniq_owner_email"
            ),
        ),
    ]
