# Generated by Django 5.2.5 on 2025-08-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_client_uniq_owner_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={
                "ordering": ["-date"],
                "permissions": [
                    ("view_all_attempts", "Может просматривать все попытки")
                ],
                "verbose_name": "попытка",
                "verbose_name_plural": "попытки",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "permissions": [
                    ("view_all_clients", "Может просматривать всех клиентов")
                ],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["start_time"],
                "permissions": [
                    ("view_all_mailings", "Может просматривать все рассылки")
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
