# Generated by Django 5.2.5 on 2025-08-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0007_alter_attempt_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["topic"],
                "permissions": (
                    ("view_all_messages", "Может просматривать все сообщения"),
                ),
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
    ]
